name: Create Resource Pack Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:  # Allows manual triggering

permissions:
  contents: write
  actions: read

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
    - name: Create Resource Pack Archive
      uses: thedoctor0/zip-release@0.7.5
      with:
        type: 'zip'
        filename: 'release.zip'
        exclusions: |
          *.git*
          *.github*
          *node_modules*
          *.editorconfig
          *.gitignore
          *.md
          README*
          LICENSE*
          .DS_Store
          Thumbs.db
    
    - name: Verify archive contents
      run: |
        echo "Archive created successfully!"
        ls -la release.zip
        unzip -l release.zip | head -20
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: release
        name: "Latest Resource Pack Release"
        body: |
          🎮 **Cobblemon Rivals Resource Pack**
          
          Automatically generated resource pack for Minecraft servers.
          
          **Usage:**
          - Download `release.zip` and upload to your server
          - Or use the direct URL in ForcePacks: `https://github.com/${{ github.repository }}/releases/download/release/release.zip`
          
          **Generated:** ${{ github.run_id }}
          **Commit:** ${{ github.sha }}
        files: |
          release.zip
        prerelease: false
        make_latest: true
        generate_release_notes: false
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}